### ISSUE TITLE
[FR] Add support for friendly_name (and optionally friendly_json)

### ISSUE THREAD

**Issue by augustozanellato** [cmusatyalab/wireguard-tools#4]
Some wireguard monitoring tools (notably [prometheus-wireguard-exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter)) support a `friendly_name` comment in the peer section of a wireguard configuration file that is used name the corresponding peer in exported metrics. In addition to that there's the even more non standard `friendly_json` comment that allows for arbitrary json tags.

A "generic" implementation that allows for setting one or more generic comments under a `[Peer]` section would also work fine for me personally.

My use case is using `wireguard-tools` in a wg config generator I'm writing for a Capture The Flag platform I'm working on :)

Example config file (taken from [here](https://github.com/MindFlavor/prometheus_wireguard_exporter/blob/2d82a9c06c3262867322519970865dbcc6e5b93b/README.md#friendly-tags)):
```
[Peer]
# friendly_name = frcognowin10
PublicKey = lqYcojJMsIZXMUw1heAFbQHBoKjCEaeo7M1WXDh/KWc=
AllowedIPs = 10.70.0.40/32
```
Example with `friendly_json` (taken from [here](https://github.com/MindFlavor/prometheus_wireguard_exporter/blob/2d82a9c06c3262867322519970865dbcc6e5b93b/src/wireguard_config.rs#L228C1-L232C26)):
```
[Peer]
# friendly_json={"id":482217555,"username":"DrProxyMeCoordinator", "first_name": "Coordinator", "last_name": "DrProxy.me" ,"auth_date":1614869789}
PublicKey = L2UoJZN7RmEKsMmqaJgKG0m1S2Zs2wd2ptAf+kb3008=
AllowedIPs = 10.70.0.4/32
```

**Comment by jaharkes** [comment]
I pushed a work-in-progress branch named "friendly_name" that tries to add handling of both friendly_name and friendly_json to the wgconfig parser/generator. Haven't run it through my pre-commit checks yet because the python version on my laptop was too old and it is still missing documentation.

**Comment by jaharkes** [comment]
Thanks for the heads up, that is what I get for not actually testing if it still works on py37. I will fix that before actually pushing it to the main branch.

**Comment by augustozanellato** [comment]
> Thanks for the heads up, that is what I get for not actually testing if it still works on py37. I will fix that before actually pushing it to the main branch.

Would a PR with a CI pipeline that runs pre-commit checks and a test matrix on all the supported Python versions be appreciated? I'd be happy to contribute that :)

**Comment by jaharkes** [comment]
CI pipeline would be nice. Although pre-commit won't work in python < 3.8.1 because of the pyupgrade and flake8 hooks that dropped support for those.

I just installed 3.7.17 locally and ran pytest and mypy check and somewhat surprisingly it found no problems. I think it is because I'm using `from __future__ import annnotations` which was introduced in python 3.7. It avoids runtime evaluation of the function annotations so all those `type | type` annotations are just stuffed into a string form as the __annotations__ attribute and as long as mypy is new enough it doesn't care if that is using Union or |.

**Comment by augustozanellato** [comment]
> CI pipeline would be nice. Although pre-commit won't work in python < 3.8.1 because of the pyupgrade and flake8 hooks that dropped support for those.

Yeah, I was thinking about running pre-commit only on latest. 

> I just installed 3.7.17 locally and ran pytest and mypy check and somewhat surprisingly it found no problems. I think it is because I'm using `from __future__ import annnotations` which was introduced in python 3.7. It avoids runtime evaluation of the function annotations so all those `type | type` annotations are just stuffed into a string form as the `__annotations__` attribute and as long as mypy is new enough it doesn't care if that is using Union or |.

That would definitely make sense!

**Comment by jaharkes** [comment]
`# friendly_name` is now supported with the release of wireguard-tools v0.4.4
